image: alpine:latest

variables:
  # KUBE_INGRESS_BASE_DOMAIN is the application deployment domain and should be set as a variable at the group or project level.
  KUBE_INGRESS_BASE_DOMAIN: nonprod.tower.cdrentertainment.com
  POSTGRES_ENABLED: "false"
  HELM_SCALE_EXTRA_ARGS: --set postgresql.enabled="false" 
  K8S_SECRET_XMS: "256m"
  K8S_SECRET_XMX: "256m"
  K8S_SECRET_MAXPERM: "64m"
  K8S_SECRET_RUMBLE_CONFIG_SERVICE_URL: "https://config-service.cdrentertainment.com/"
  K8S_SECRET_RUMBLE_COMPONENT: "player-service"
  K8S_SECRET_RUMBLE_DEPLOYMENT: "107"
  K8S_SECRET_LOGGLY_URL: "https://logs-01.loggly.com/bulk/f91d5019-e31d-4955-812c-31891b64b8d9/tag/player-service/"
  K8S_SECRET_GRAPHITE: "graphite.rumblegames.com:2003"
  K8S_SECRET_GOOGLE_APP_ID: "5861154319-vcerqf8f392hj9q7dphljk1d70hdsm3l.apps.googleusercontent.com"
  K8S_SECRET_GOOGLE_CLIENT_ID: "5861154319-vcerqf8f392hj9q7dphljk1d70hdsm3l.apps.googleusercontent.com"
  K8S_SECRET_GOOGLE_VALIDATE_TOKEN_URL: "https://www.googleapis.com/games/v1/applications/"
  K8S_SECRET_MONGODB_NAME: "player-service-107"
  K8S_SECRET_FB_APP_ID: "NOT_AVAILABLE"
  K8S_SECRET_FB_APP_SECRET: "NOT_AVAILABLE"
  K8S_SECRET_FB_VALIDATE_TOKEN_URL: "https://graph.facebook.com/me"
  K8S_SECRET_GEO_IP_S3_BUCKET: "rumble-lab-geoip"
  K8S_SECRET_GEO_IP_S3_KEY: "GeoIP2-Country.mmdb"
  K8S_SECRET_GEO_IP_S3_REGION: "us-east-1"
  # from gitlab project ci variables
  K8S_SECRET_RUMBLE_KEY: "$RUMBLE_KEY"
  K8S_SECRET_GAME_GUKEY: "$GAME_GUKEY"
  K8S_SECRET_GOOGLE_APP_SECRET: "$GOOGLE_APP_SECRET"
  K8S_SECRET_MONGODB_URI: "$MONGODB_URI"


  DOCKER_DRIVER: overlay2
  DEPLOY_TYPE: "kubernetes" # "kubernetes"

  ROLLOUT_RESOURCE_TYPE: deployment

  DOCKER_TLS_CERTDIR: ""  # https://gitlab.com/gitlab-org/gitlab-runner/issues/4501

stages:
  - app_build
  - build
  - deploy  # dummy stage to follow the template guidelines
  - dev
  - staging
  - production
  - performance
  - cleanup

build_app:
  stage: app_build
  image: gradle:6-jdk8
  allow_failure: false
  tags:
    - kubernetes
  cache:
    key: player-service
    paths:
      - .gradle
  script:
    - apt-get update -yq
    - apt install zip
    - chmod +x ./gradlew
    - ./gradlew assemble
    - rm -f ~/.gradle/caches/modules-2/modules-2.lock
    - rm -f ~/.gradle/caches/modules-2/gc.properties
  artifacts:
    paths:
      - build/libs/*.war


build_image:
  stage: build
  allow_failure: false
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
  rules:
    - if: '$BUILD_DISABLED'
      when: never
    - if: $DEPLOY_TYPE == "beanstalk"
      when: never
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH'
    - if: $DEPLOY_TYPE == "kubernetes"
      when: always
  needs:
    - job: build_app
      artifacts: true

include: 
  - '/.gitlab/deploy-eb.yaml'
  - '/.gitlab/deploy-k8s.yaml'
