version: 0.2

proxy:
    upload-artifacts: yes
    logs: yes
            
phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - ./gradlew assemble
artifacts:
  files:
    - .ebextensions/**/*
    - build/libs/*.war

